### PR TITLE
Fixes #62 in a simpler way

### LINKED ISSUE #62: getStoredFile() fails
### Description:
Asterisk 14 introduces the [ability to fetch a recording file](https://wiki.asterisk.org/wiki/display/AST/Asterisk+14+Recordings+REST+API#Asterisk14RecordingsRESTAPI-getStoredFile:GET/recordings/stored/{recordingName}/file), which is transmitted in binary.

The `getStoredFile()` method fails with the following error:

> RIFFd`
> ^
> 
> SyntaxError: Unexpected token R in JSON at position 0
>     at Object.parse (native)
>     at SwaggerRequest.processResponse (/myapp/node_modules/ari-client/lib/client.js:261:31)
>     at Object.response (/myapp/node_modules/swagger-client/lib/swagger.js:1086:24)
>     at EventEmitter.response (/myapp/node_modules/swagger-client/lib/swagger.js:1308:19)
>     at emitOne (events.js:96:13)
>     at EventEmitter.emit (events.js:188:7)
>     at emit (/myapp/node_modules/shred/lib/shred/request.js:456:21)
>     at /myapp/node_modules/shred/lib/shred/request.js:476:9
>     at setBodyAndFinish (/myapp/node_modules/shred/lib/shred/response.js:103:7)
>     at IncomingMessage.<anonymous> (/myapp/node_modules/shred/lib/shred/response.js:120:7)
>     at emitNone (events.js:91:20)
>     at IncomingMessage.emit (events.js:185:7)
>     at endReadableNT (_stream_readable.js:974:12)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)

I've tracked this error to [JSON.parse(result)](https://github.com/asterisk/node-ari-client/blob/master/lib/client.js#L261) attempting to parse a non-JSON binary string, instead of handling the `Buffer` object.

### PR DESCRIPTION
**Pull request by mpotra**
Fixes #62 and replaces PR #63

### CODE REVIEW

**Comment by chadxz** [comment]
@samuelg @danjenkins care to review?

**Comment by mpotra** [comment]
@chadxz On a second look, indeed it makes more sense to leave that bit in place, just in case `binary` will ever get added to the known types. Plus, it makes for a smaller and cleaner commit.
I've just updated with a squashed commit.

**Comment by chadxz** [comment]
looks great, thanks!

**Comment by chadxz** [comment]
Going to wait and make sure @samuelg doesn't have any thoughts to add, then will merge.

**Comment by samuelg** [comment]
Looks good to me!

**Comment by chadxz** [comment]
released as v1.1.0

**Pull request merged**
