### PR TITLE
Send an error when the host is not reachable.

### PR DESCRIPTION
**Pull request by samuelg**
Currently, swagger reports errors once a connection has been established (such as an authentication failure), but not before. If a user attempts to connect to a host that does not exist, ari-client does not report that an error occured. This PR fixes this by first connecting to the host using request. If the host is not reachable, the error is reported. Otherwise, the swagger connection is established as it is today.

A test is also included to ensure that connecting to a bad host will result in the expected error being passed to the callback passed in to the client._attachApi method.

### CODE REVIEW

**Comment by MattRiddell** [comment]
So then nobody has a patch that works?

**Comment by samuelg** [comment]
It does work, but I also wanted to handle timeouts. I started rebasing off of master and added that some time ago, just need to carve out some time after hours to finish it.

**Comment by TomDmitriev** [comment]
This is a highly needed patch! Meanwhile, does anybody know a workaround?

**Comment by ibc** [comment]
Workaround here: http://chadmcelligott.com/awry/

NOTE: `node-ari-client`code quality is not acceptable. A library that does not allow catching a WebSocket initial connection is far for usable. If this is because it is built with swagger-js, then don't use swagger-js.

**Comment by jp1987** [comment]
Any progress on this?

**Comment by ibc** [comment]
Hi Dan, what about moving to http://chadmcelligott.com/awry/ ?

**Comment by samuelg** [comment]
#109 fixes this issue. Putting this PR out of its misery.

**Pull request closed without merging**
