### PR TITLE
if the protocol is https, use wss instead of ws

### PR DESCRIPTION
**Pull request by danjenkins**
fixes #58

### CODE REVIEW

**Comment by chadxz** [comment]
seems legit 👍

**Comment by chadxz** [comment]
can you write a simple test that asserts the feature? You'll probably need to generate a self-signed cert to use for the websocket server to use. If  you don't have time or whatever just let us know we might could help out.

**Comment by chadxz** [comment]
I talked to Sam about this and his sentiment is that the default behavior is to fall back to the old behavior, so it's probably okay without a test.

**Comment by samuelg** [comment]
Feel free to merge away. We can then bump the patch version and deploy to npm.

**Comment by chadxz** [comment]
Or we can just add you on npm

**Comment by chadxz** [comment]
done

**Comment by chadxz** [comment]
🎉

**Pull request merged**
